//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Amway.OA.ETOffine.Entities;

namespace Amway.OA.ETOffine.BLL
{
	/// <summary>
	/// MsetOfflineTicket业务逻辑组件接口
	/// </summary>
	public partial interface IMsetOfflineTicketBO : IBO<MsetOfflineTicket>
	{
	}
}
