//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amway.OA.ETOffine.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class ETOfflineContext : DbContext
    {
        public ETOfflineContext() : base("name=ETOffineEntities")
        {
    
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {       
            base.OnModelCreating(modelBuilder);
    
    		modelBuilder.Configurations.Add(new MsetOfflineActivityMap());
    		modelBuilder.Configurations.Add(new MsetOfflineCheckingLogMap());
    		modelBuilder.Configurations.Add(new MsetOfflineTicketMap());
    	}
    }
}
