//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Objects;
using Amway.OA.ETOffine;
using Amway.OA.ETOffine.DAL;
using Amway.OA.ETOffine.Entities;
using System.Data.Entity.ModelConfiguration;

namespace Amway.OA.ETOffine.DAL
{
	/// <summary>
	/// MsetOfflineTicket数据访问组件
	/// </summary>
	public class MsetOfflineTicketMap : EntityTypeConfiguration<MsetOfflineTicket>
	{
		public MsetOfflineTicketMap()
		{
			this.ToTable("TSTB_MSET_OFFLINE_TICKET");

			this.Property(t => t.ID).HasColumnName("ID");
			this.Property(t => t.RecordID).HasColumnName("RECORD_ID");
			this.Property(t => t.TicketID).HasColumnName("TICKET_ID");
			this.Property(t => t.TicketSn).HasColumnName("TICKET_SN");
			this.Property(t => t.Category).HasColumnName("CATEGORY");
			this.Property(t => t.TicketStatus).HasColumnName("TICKET_STATUS");
			this.Property(t => t.CheckinIp).HasColumnName("CHECKIN_IP");
			this.Property(t => t.MachineName).HasColumnName("MACHINE_NAME");
			this.Property(t => t.CheckinTime).HasColumnName("CHECKIN_TIME");
			this.Property(t => t.AdaCard).HasColumnName("ADA_CARD");
			this.Property(t => t.OwnerName).HasColumnName("OWNER_NAME");
			this.Property(t => t.ImportTime).HasColumnName("IMPORT_TIME");
			this.Property(t => t.Status).HasColumnName("STATUS");
			this.Property(t => t.SyncDate).HasColumnName("SYNC_DATE");
			this.Property(t => t.SyncStatus).HasColumnName("SYNC_STATUS");
		}
	}
}
