//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Objects;
using Amway.OA.ETOffine;
using Amway.OA.ETOffine.DAL;
using Amway.OA.ETOffine.Entities;
using System.Data.Entity.ModelConfiguration;

namespace Amway.OA.ETOffine.DAL
{
	/// <summary>
	/// MsetOfflineActivity数据访问组件
	/// </summary>
	public class MsetOfflineActivityMap : EntityTypeConfiguration<MsetOfflineActivity>
	{
		public MsetOfflineActivityMap()
		{
			this.ToTable("TSTB_MSET_OFFLINE_ACTIVITY");

			this.Property(t => t.ID).HasColumnName("ID");
			this.Property(t => t.RecordID).HasColumnName("RECORD_ID");
			this.Property(t => t.ActivitySn).HasColumnName("ACTIVITY_SN");
			this.Property(t => t.ActivityName).HasColumnName("ACTIVITY_NAME");
			this.Property(t => t.IsRealName).HasColumnName("IS_REAL_NAME");
			this.Property(t => t.CheckingStatus).HasColumnName("CHECKING_STATUS");
			this.Property(t => t.TicketCount).HasColumnName("TICKET_COUNT");
			this.Property(t => t.ActivityPeopleCount).HasColumnName("ACTIVITY_PEOPLE_COUNT");
			this.Property(t => t.ActivityCity).HasColumnName("ACTIVITY_CITY");
			this.Property(t => t.ActivityAddr).HasColumnName("ACTIVITY_ADDR");
			this.Property(t => t.StartTime).HasColumnName("START_TIME");
			this.Property(t => t.EndTime).HasColumnName("END_TIME");
			this.Property(t => t.ActivityCategory).HasColumnName("ACTIVITY_CATEGORY");
			this.Property(t => t.ActivityDetail).HasColumnName("ACTIVITY_DETAIL");
			this.Property(t => t.ActivitySubDetail).HasColumnName("ACTIVITY_SUB_DETAIL");
			this.Property(t => t.Creator).HasColumnName("CREATOR");
			this.Property(t => t.CreateDate).HasColumnName("CREATE_DATE");
			this.Property(t => t.Updator).HasColumnName("UPDATOR");
			this.Property(t => t.UpdateDate).HasColumnName("UPDATE_DATE");
			this.Property(t => t.Status).HasColumnName("STATUS");
			this.Property(t => t.SyncDate).HasColumnName("SYNC_DATE");
			this.Property(t => t.SyncStatus).HasColumnName("SYNC_STATUS");
			this.Property(t => t.HostIp).HasColumnName("HOST_IP");
			this.Property(t => t.IsHost).HasColumnName("IS_HOST");
			this.Property(t => t.UpdateHostTime).HasColumnName("UPDATE_HOST_TIME");
		}
	}
}
