//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Objects;
using Amway.OA.ETOffine;
using Amway.OA.ETOffine.DAL;
using Amway.OA.ETOffine.Entities;

namespace Amway.OA.ETOffine.DAL
{
	/// <summary>
	/// MsetOfflineCheckingLog数据访问组件
	/// </summary>
	public partial class MsetOfflineCheckingLogDAO : DAOBase<MsetOfflineCheckingLog> , IMsetOfflineCheckingLogDAO
	{
	}
}
