//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amway.OA.ETOffine.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using System.ComponentModel;
    
    
    [Serializable]
    public partial class MsetOfflineActivity:EntitieBase
    {
        private Nullable<Int64> _ID;	
    	override public Nullable<Int64> ID 
    	{ 
    	    get
    		{
    		   return _ID;
    		}
    	    set
    	    {
    			_ID = value;
    			this.MarkPropertyChange("ID");	
    		}
    	}
    
        private string _RecordID;	
    	public string RecordID 
    	{ 
    	    get
    		{
    		   return _RecordID;
    		}
    	    set
    	    {
    			_RecordID = value;
    			this.MarkPropertyChange("RecordID");	
    		}
    	}
    
        private string _ActivitySn;	
    	public string ActivitySn 
    	{ 
    	    get
    		{
    		   return _ActivitySn;
    		}
    	    set
    	    {
    			_ActivitySn = value;
    			this.MarkPropertyChange("ActivitySn");	
    		}
    	}
    
        private string _ActivityName;	
    	public string ActivityName 
    	{ 
    	    get
    		{
    		   return _ActivityName;
    		}
    	    set
    	    {
    			_ActivityName = value;
    			this.MarkPropertyChange("ActivityName");	
    		}
    	}
    
        private Nullable<int> _IsRealName;	
    	public Nullable<int> IsRealName 
    	{ 
    	    get
    		{
    		   return _IsRealName;
    		}
    	    set
    	    {
    			_IsRealName = value;
    			this.MarkPropertyChange("IsRealName");	
    		}
    	}
    
        private Nullable<int> _CheckingStatus;	
    	public Nullable<int> CheckingStatus 
    	{ 
    	    get
    		{
    		   return _CheckingStatus;
    		}
    	    set
    	    {
    			_CheckingStatus = value;
    			this.MarkPropertyChange("CheckingStatus");	
    		}
    	}
    
        private Nullable<int> _TicketCount;	
    	public Nullable<int> TicketCount 
    	{ 
    	    get
    		{
    		   return _TicketCount;
    		}
    	    set
    	    {
    			_TicketCount = value;
    			this.MarkPropertyChange("TicketCount");	
    		}
    	}
    
        private Nullable<int> _ActivityPeopleCount;	
    	public Nullable<int> ActivityPeopleCount 
    	{ 
    	    get
    		{
    		   return _ActivityPeopleCount;
    		}
    	    set
    	    {
    			_ActivityPeopleCount = value;
    			this.MarkPropertyChange("ActivityPeopleCount");	
    		}
    	}
    
        private string _ActivityCity;	
    	public string ActivityCity 
    	{ 
    	    get
    		{
    		   return _ActivityCity;
    		}
    	    set
    	    {
    			_ActivityCity = value;
    			this.MarkPropertyChange("ActivityCity");	
    		}
    	}
    
        private string _ActivityAddr;	
    	public string ActivityAddr 
    	{ 
    	    get
    		{
    		   return _ActivityAddr;
    		}
    	    set
    	    {
    			_ActivityAddr = value;
    			this.MarkPropertyChange("ActivityAddr");	
    		}
    	}
    
        private Nullable<System.DateTime> _StartTime;	
    	public Nullable<System.DateTime> StartTime 
    	{ 
    	    get
    		{
    		   return _StartTime;
    		}
    	    set
    	    {
    			_StartTime = value;
    			this.MarkPropertyChange("StartTime");	
    		}
    	}
    
        private Nullable<System.DateTime> _EndTime;	
    	public Nullable<System.DateTime> EndTime 
    	{ 
    	    get
    		{
    		   return _EndTime;
    		}
    	    set
    	    {
    			_EndTime = value;
    			this.MarkPropertyChange("EndTime");	
    		}
    	}
    
        private string _ActivityCategory;	
    	public string ActivityCategory 
    	{ 
    	    get
    		{
    		   return _ActivityCategory;
    		}
    	    set
    	    {
    			_ActivityCategory = value;
    			this.MarkPropertyChange("ActivityCategory");	
    		}
    	}
    
        private string _ActivityDetail;	
    	public string ActivityDetail 
    	{ 
    	    get
    		{
    		   return _ActivityDetail;
    		}
    	    set
    	    {
    			_ActivityDetail = value;
    			this.MarkPropertyChange("ActivityDetail");	
    		}
    	}
    
        private string _ActivitySubDetail;	
    	public string ActivitySubDetail 
    	{ 
    	    get
    		{
    		   return _ActivitySubDetail;
    		}
    	    set
    	    {
    			_ActivitySubDetail = value;
    			this.MarkPropertyChange("ActivitySubDetail");	
    		}
    	}
    
        private string _Creator;	
    	public string Creator 
    	{ 
    	    get
    		{
    		   return _Creator;
    		}
    	    set
    	    {
    			_Creator = value;
    			this.MarkPropertyChange("Creator");	
    		}
    	}
    
        private Nullable<System.DateTime> _CreateDate;	
    	public Nullable<System.DateTime> CreateDate 
    	{ 
    	    get
    		{
    		   return _CreateDate;
    		}
    	    set
    	    {
    			_CreateDate = value;
    			this.MarkPropertyChange("CreateDate");	
    		}
    	}
    
        private string _Updator;	
    	public string Updator 
    	{ 
    	    get
    		{
    		   return _Updator;
    		}
    	    set
    	    {
    			_Updator = value;
    			this.MarkPropertyChange("Updator");	
    		}
    	}
    
        private Nullable<System.DateTime> _UpdateDate;	
    	public Nullable<System.DateTime> UpdateDate 
    	{ 
    	    get
    		{
    		   return _UpdateDate;
    		}
    	    set
    	    {
    			_UpdateDate = value;
    			this.MarkPropertyChange("UpdateDate");	
    		}
    	}
    
        private int _Status;	
    	public int Status 
    	{ 
    	    get
    		{
    		   return _Status;
    		}
    	    set
    	    {
    			_Status = value;
    			this.MarkPropertyChange("Status");	
    		}
    	}
    
        private Nullable<System.DateTime> _SyncDate;	
    	override public Nullable<System.DateTime> SyncDate 
    	{ 
    	    get
    		{
    		   return _SyncDate;
    		}
    	    set
    	    {
    			_SyncDate = value;
    			this.MarkPropertyChange("SyncDate");	
    		}
    	}
    
        private int _SyncStatus;	
    	override public int SyncStatus 
    	{ 
    	    get
    		{
    		   return _SyncStatus;
    		}
    	    set
    	    {
    			_SyncStatus = value;
    			this.MarkPropertyChange("SyncStatus");	
    		}
    	}
    
        private string _HostIp;	
    	public string HostIp 
    	{ 
    	    get
    		{
    		   return _HostIp;
    		}
    	    set
    	    {
    			_HostIp = value;
    			this.MarkPropertyChange("HostIp");	
    		}
    	}
    
        private int _IsHost;	
    	public int IsHost 
    	{ 
    	    get
    		{
    		   return _IsHost;
    		}
    	    set
    	    {
    			_IsHost = value;
    			this.MarkPropertyChange("IsHost");	
    		}
    	}
    
        private Nullable<System.DateTime> _UpdateHostTime;	
    	public Nullable<System.DateTime> UpdateHostTime 
    	{ 
    	    get
    		{
    		   return _UpdateHostTime;
    		}
    	    set
    	    {
    			_UpdateHostTime = value;
    			this.MarkPropertyChange("UpdateHostTime");	
    		}
    	}
    
    }
}
