//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amway.OA.ETOffine.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using System.ComponentModel;
    
    
    [Serializable]
    public partial class MsetOfflineTicket:EntitieBase
    {
        private Nullable<Int64> _ID;	
    	override public Nullable<Int64> ID 
    	{ 
    	    get
    		{
    		   return _ID;
    		}
    	    set
    	    {
    			_ID = value;
    			this.MarkPropertyChange("ID");	
    		}
    	}
    
        private string _RecordID;	
    	public string RecordID 
    	{ 
    	    get
    		{
    		   return _RecordID;
    		}
    	    set
    	    {
    			_RecordID = value;
    			this.MarkPropertyChange("RecordID");	
    		}
    	}
    
        private string _TicketID;	
    	public string TicketID 
    	{ 
    	    get
    		{
    		   return _TicketID;
    		}
    	    set
    	    {
    			_TicketID = value;
    			this.MarkPropertyChange("TicketID");	
    		}
    	}
    
        private string _TicketSn;	
    	public string TicketSn 
    	{ 
    	    get
    		{
    		   return _TicketSn;
    		}
    	    set
    	    {
    			_TicketSn = value;
    			this.MarkPropertyChange("TicketSn");	
    		}
    	}
    
        private string _Category;	
    	public string Category 
    	{ 
    	    get
    		{
    		   return _Category;
    		}
    	    set
    	    {
    			_Category = value;
    			this.MarkPropertyChange("Category");	
    		}
    	}
    
        private Nullable<int> _TicketStatus;	
    	public Nullable<int> TicketStatus 
    	{ 
    	    get
    		{
    		   return _TicketStatus;
    		}
    	    set
    	    {
    			_TicketStatus = value;
    			this.MarkPropertyChange("TicketStatus");	
    		}
    	}
    
        private string _CheckinIp;	
    	public string CheckinIp 
    	{ 
    	    get
    		{
    		   return _CheckinIp;
    		}
    	    set
    	    {
    			_CheckinIp = value;
    			this.MarkPropertyChange("CheckinIp");	
    		}
    	}
    
        private string _MachineName;	
    	public string MachineName 
    	{ 
    	    get
    		{
    		   return _MachineName;
    		}
    	    set
    	    {
    			_MachineName = value;
    			this.MarkPropertyChange("MachineName");	
    		}
    	}
    
        private Nullable<System.DateTime> _CheckinTime;	
    	public Nullable<System.DateTime> CheckinTime 
    	{ 
    	    get
    		{
    		   return _CheckinTime;
    		}
    	    set
    	    {
    			_CheckinTime = value;
    			this.MarkPropertyChange("CheckinTime");	
    		}
    	}
    
        private string _AdaCard;	
    	public string AdaCard 
    	{ 
    	    get
    		{
    		   return _AdaCard;
    		}
    	    set
    	    {
    			_AdaCard = value;
    			this.MarkPropertyChange("AdaCard");	
    		}
    	}
    
        private string _OwnerName;	
    	public string OwnerName 
    	{ 
    	    get
    		{
    		   return _OwnerName;
    		}
    	    set
    	    {
    			_OwnerName = value;
    			this.MarkPropertyChange("OwnerName");	
    		}
    	}
    
        private Nullable<System.DateTime> _ImportTime;	
    	public Nullable<System.DateTime> ImportTime 
    	{ 
    	    get
    		{
    		   return _ImportTime;
    		}
    	    set
    	    {
    			_ImportTime = value;
    			this.MarkPropertyChange("ImportTime");	
    		}
    	}
    
        private int _Status;	
    	public int Status 
    	{ 
    	    get
    		{
    		   return _Status;
    		}
    	    set
    	    {
    			_Status = value;
    			this.MarkPropertyChange("Status");	
    		}
    	}
    
        private Nullable<System.DateTime> _SyncDate;	
    	override public Nullable<System.DateTime> SyncDate 
    	{ 
    	    get
    		{
    		   return _SyncDate;
    		}
    	    set
    	    {
    			_SyncDate = value;
    			this.MarkPropertyChange("SyncDate");	
    		}
    	}
    
        private int _SyncStatus;	
    	override public int SyncStatus 
    	{ 
    	    get
    		{
    		   return _SyncStatus;
    		}
    	    set
    	    {
    			_SyncStatus = value;
    			this.MarkPropertyChange("SyncStatus");	
    		}
    	}
    
    }
}
