1.求某列重复值
SELECT TICKET_CATEGORY
  FROM dbo.TSTB_MSET_TICKET_CATEGORY 
  GROUP BY TICKET_CATEGORY
  HAVING COUNT(TICKET_CATEGORY) > 1
2.增加字段：
	IF NOT EXISTS ( SELECT  d.name ,
			    a.*
		    FROM    sys.syscolumns a
			    INNER JOIN sysobjects d ON a.id = d.id
						       AND d.xtype = 'U'
						       AND d.name <> 'dtproperties'
		    WHERE   a.name = 'ENABLE_PRESENT'
			    AND d.name = 'TSTB_MSAT_ACTIVITY_INFO' ) 
	    ALTER TABLE TSTB_MSAT_ACTIVITY_INFO ADD ENABLE_PRESENT bit NULL
	GO
3.更改注释：
	表：
	EXEC sp_addextendedproperty 'MS_Description', '手机助手活动信息', 'Schema', dbo, 'table', TSTB_MSAT_ACTIVITY_INFO
	字段：
	EXEC sp_addextendedproperty 'MS_Description', '活动编号', 'Schema', dbo, 'table', TSTB_MSAT_ACTIVITY_INFO, 'column', ACTIVITY_SN
4.加排序列：
5.修改字段默认值([ATTENDEE_STATUS])（0->10)
	ALTER TABLE [dbo].[TSTB_MSAD_MEETINFO] DROP CONSTRAINT [DF__TSTB_MSAD__ATTEN__639117B7]
	ALTER TABLE [dbo].[TSTB_MSAD_MEETINFO] ADD CONSTRAINT [DF__TSTB_MSAD__ATTEN__639117B7]  DEFAULT ((10)) FOR [ATTENDEE_STATUS]
	GO
6.添加已有字段默认值：
	alter table dbo.TSTB_MSAD_ATTENDEES_INFO 
	add constraint defaultValue default 0 for CHARGE_STATUS
7.如果存在则更新否则插入：
	IF EXISTS (SELECT 1 FROM [MSTB_COM_BASE_DATA] WHERE [BASE_DATA_ID]='9dca098b-3812-49dd-800d-9b2ff51398f7')
	  UPDATE [MSTB_COM_BASE_DATA] SET [SYSTEM_ID]='e4ce6950-0321-4bf0-b028-583fac3f02d9',[BASE_DATA_CODE]='MSAT_MessageSetting',[BASE_DATA_NAME_EN]='MessageSetting',[BASE_DATA_NAME_CHS]='手机助手推送消息设置',[BASE_DATA_NAME_CHT]='手機助手推送消息設置',[DATA_SOURCE_TYPE]='0',[CACHE_TIME]=0,[DB_TYPE]='',[DB_CONN_STRING]=NULL,[DB_SQL_STATEMENT]='',[WS_URL]='',[WS_METHOD]='',[WS_USERNAME]='',[WS_PASSWORD]='',[DESCR]='',[STATUS]=1,[CREATOR]='cn088777',[CREATE_DATE]='2015-01-15 10:37:34',[UPDATOR]='cn088777',[UPDATE_DATE]='2015-01-15 10:37:34' WHERE [BASE_DATA_ID]='9dca098b-3812-49dd-800d-9b2ff51398f7';
	ELSE
	  INSERT INTO [MSTB_COM_BASE_DATA] ([BASE_DATA_ID],[SYSTEM_ID],[BASE_DATA_CODE],[BASE_DATA_NAME_EN],[BASE_DATA_NAME_CHS],[BASE_DATA_NAME_CHT],[DATA_SOURCE_TYPE],[CACHE_TIME],[DB_TYPE],[DB_CONN_STRING],[DB_SQL_STATEMENT],[WS_URL],[WS_METHOD],[WS_USERNAME],[WS_PASSWORD],[DESCR],[STATUS],[CREATOR],[CREATE_DATE],[UPDATOR],[UPDATE_DATE]) VALUES ('9dca098b-3812-49dd-800d-9b2ff51398f7','e4ce6950-0321-4bf0-b028-583fac3f02d9','MSAT_MessageSetting','MessageSetting','手机助手推送消息设置','手機助手推送消息設置','0',0,'',NULL,'','','','','','',1,'cn088777','2015-01-15 10:37:34','cn088777','2015-01-15 10:37:34');
8.设置主键：
	ALTER TABLE TSTB_MSAT_ACTIVITY_INFO ADD CONSTRAINT PK_TSTB_MSAT_ACTIVITY_INFO 
		PRIMARY KEY CLUSTERED (RECORD_ID)
	;
