//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Amway.OA.ETOffine.Entities;

namespace Amway.OA.ETOffine.DAL
{
	/// <summary>
	/// MsetOfflineTicket数据访问组件接口
	/// </summary>
	public partial interface IMsetOfflineTicketDAO : IDAO<MsetOfflineTicket>
	{
	}
}
