//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace Amway.OA.ETOffine.Web.MSETOfflineService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OffineWebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MsetCKActivityInfoDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameValue[]))]
    public partial class OffineWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NoticeOperationCompleted;
        
        private WsSecurityHeader wsSecurityHeaderValueField;
        
        private System.Threading.SendOrPostCallback DownLoadActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadActivityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OffineWebService() {
            this.Url = global::Amway.OA.ETOffine.Web.Properties.Settings.Default.Amway_OA_ETOffine_Web_MSETOfflineService_OffineWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public WsSecurityHeader WsSecurityHeaderValue {
            get {
                return this.wsSecurityHeaderValueField;
            }
            set {
                this.wsSecurityHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NoticeCompletedEventHandler NoticeCompleted;
        
        /// <remarks/>
        public event DownLoadActivityCompletedEventHandler DownLoadActivityCompleted;
        
        /// <remarks/>
        public event UploadActivityCompletedEventHandler UploadActivityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Notice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Notice(string recordId, string workflowInfoId, string empNumber, int AgileEventType, string agileWorkCode, NameValue[] customAttribute) {
            object[] results = this.Invoke("Notice", new object[] {
                        recordId,
                        workflowInfoId,
                        empNumber,
                        AgileEventType,
                        agileWorkCode,
                        customAttribute});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NoticeAsync(string recordId, string workflowInfoId, string empNumber, int AgileEventType, string agileWorkCode, NameValue[] customAttribute) {
            this.NoticeAsync(recordId, workflowInfoId, empNumber, AgileEventType, agileWorkCode, customAttribute, null);
        }
        
        /// <remarks/>
        public void NoticeAsync(string recordId, string workflowInfoId, string empNumber, int AgileEventType, string agileWorkCode, NameValue[] customAttribute, object userState) {
            if ((this.NoticeOperationCompleted == null)) {
                this.NoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNoticeOperationCompleted);
            }
            this.InvokeAsync("Notice", new object[] {
                        recordId,
                        workflowInfoId,
                        empNumber,
                        AgileEventType,
                        agileWorkCode,
                        customAttribute}, this.NoticeOperationCompleted, userState);
        }
        
        private void OnNoticeOperationCompleted(object arg) {
            if ((this.NoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NoticeCompleted(this, new NoticeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("WsSecurityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownLoadActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ETOffineActivityDTO DownLoadActivity(string rid) {
            object[] results = this.Invoke("DownLoadActivity", new object[] {
                        rid});
            return ((ETOffineActivityDTO)(results[0]));
        }
        
        /// <remarks/>
        public void DownLoadActivityAsync(string rid) {
            this.DownLoadActivityAsync(rid, null);
        }
        
        /// <remarks/>
        public void DownLoadActivityAsync(string rid, object userState) {
            if ((this.DownLoadActivityOperationCompleted == null)) {
                this.DownLoadActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownLoadActivityOperationCompleted);
            }
            this.InvokeAsync("DownLoadActivity", new object[] {
                        rid}, this.DownLoadActivityOperationCompleted, userState);
        }
        
        private void OnDownLoadActivityOperationCompleted(object arg) {
            if ((this.DownLoadActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownLoadActivityCompleted(this, new DownLoadActivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("WsSecurityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadActivity(string recordID, ETOffineTicketDTO[] ticketList) {
            object[] results = this.Invoke("UploadActivity", new object[] {
                        recordID,
                        ticketList});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadActivityAsync(string recordID, ETOffineTicketDTO[] ticketList) {
            this.UploadActivityAsync(recordID, ticketList, null);
        }
        
        /// <remarks/>
        public void UploadActivityAsync(string recordID, ETOffineTicketDTO[] ticketList, object userState) {
            if ((this.UploadActivityOperationCompleted == null)) {
                this.UploadActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadActivityOperationCompleted);
            }
            this.InvokeAsync("UploadActivity", new object[] {
                        recordID,
                        ticketList}, this.UploadActivityOperationCompleted, userState);
        }
        
        private void OnUploadActivityOperationCompleted(object arg) {
            if ((this.UploadActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadActivityCompleted(this, new UploadActivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class WsSecurityHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string appIdField;
        
        private string appKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string AppId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
            }
        }
        
        /// <remarks/>
        public string AppKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ETOffineActivityDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsetCKActivityInfoDTO {
        
        private string recordIDField;
        
        private string activitySNField;
        
        private string activityNameField;
        
        private string activityCityNameField;
        
        private string activityAddressField;
        
        private string activityChildDetailField;
        
        private System.Nullable<System.DateTime> startTimeField;
        
        private System.Nullable<System.DateTime> finishTimeField;
        
        private int activityCountField;
        
        /// <remarks/>
        public string RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
            }
        }
        
        /// <remarks/>
        public string ActivitySN {
            get {
                return this.activitySNField;
            }
            set {
                this.activitySNField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityName {
            get {
                return this.activityNameField;
            }
            set {
                this.activityNameField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityCityName {
            get {
                return this.activityCityNameField;
            }
            set {
                this.activityCityNameField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityAddress {
            get {
                return this.activityAddressField;
            }
            set {
                this.activityAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityChildDetail {
            get {
                return this.activityChildDetailField;
            }
            set {
                this.activityChildDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FinishTime {
            get {
                return this.finishTimeField;
            }
            set {
                this.finishTimeField = value;
            }
        }
        
        /// <remarks/>
        public int ActivityCount {
            get {
                return this.activityCountField;
            }
            set {
                this.activityCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ETOffineActivityDTO : MsetCKActivityInfoDTO {
        
        private string activityCategoryField;
        
        private string activityDetailField;
        
        private int isRealNameField;
        
        private int ticketCountField;
        
        private string creatorField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private string updatorField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        private ETOffineTicketDTO[] itemsField;
        
        /// <remarks/>
        public string ActivityCategory {
            get {
                return this.activityCategoryField;
            }
            set {
                this.activityCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityDetail {
            get {
                return this.activityDetailField;
            }
            set {
                this.activityDetailField = value;
            }
        }
        
        /// <remarks/>
        public int IsRealName {
            get {
                return this.isRealNameField;
            }
            set {
                this.isRealNameField = value;
            }
        }
        
        /// <remarks/>
        public int TicketCount {
            get {
                return this.ticketCountField;
            }
            set {
                this.ticketCountField = value;
            }
        }
        
        /// <remarks/>
        public string Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string Updator {
            get {
                return this.updatorField;
            }
            set {
                this.updatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        public ETOffineTicketDTO[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ETOffineTicketDTO {
        
        private string recordIDField;
        
        private string ticketIDField;
        
        private string ticketSNField;
        
        private string categoryField;
        
        private int ticketStatusField;
        
        private System.Nullable<System.DateTime> checkingTimeField;
        
        private string adaCardField;
        
        private string owner_NameField;
        
        private string checkinIPField;
        
        private string machineNameField;
        
        /// <remarks/>
        public string RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
            }
        }
        
        /// <remarks/>
        public string TicketID {
            get {
                return this.ticketIDField;
            }
            set {
                this.ticketIDField = value;
            }
        }
        
        /// <remarks/>
        public string TicketSN {
            get {
                return this.ticketSNField;
            }
            set {
                this.ticketSNField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public int TicketStatus {
            get {
                return this.ticketStatusField;
            }
            set {
                this.ticketStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CheckingTime {
            get {
                return this.checkingTimeField;
            }
            set {
                this.checkingTimeField = value;
            }
        }
        
        /// <remarks/>
        public string AdaCard {
            get {
                return this.adaCardField;
            }
            set {
                this.adaCardField = value;
            }
        }
        
        /// <remarks/>
        public string Owner_Name {
            get {
                return this.owner_NameField;
            }
            set {
                this.owner_NameField = value;
            }
        }
        
        /// <remarks/>
        public string CheckinIP {
            get {
                return this.checkinIPField;
            }
            set {
                this.checkinIPField = value;
            }
        }
        
        /// <remarks/>
        public string MachineName {
            get {
                return this.machineNameField;
            }
            set {
                this.machineNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NameValue {
        
        private string nameField;
        
        private object valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NoticeCompletedEventHandler(object sender, NoticeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NoticeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NoticeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DownLoadActivityCompletedEventHandler(object sender, DownLoadActivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownLoadActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownLoadActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ETOffineActivityDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ETOffineActivityDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UploadActivityCompletedEventHandler(object sender, UploadActivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591