//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Amway.OA.ETOffine;
using Amway.OA.ETOffine.DAL;
using Amway.OA.ETOffine.Entities;

namespace Amway.OA.ETOffine.BLL
{
	/// <summary>
	/// MsetOfflineActivity业务逻辑组件
	/// </summary>
	public partial class MsetOfflineActivityBO : BOBase<MsetOfflineActivity,IMsetOfflineActivityDAO> ,IMsetOfflineActivityBO
	{
	}
}
